# Generated by Django 6.0.4 on 2026-04-08 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='exchange',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='exchanges.exchangerequest'),
        ),
    ]
